version: '2.1'

services:
  db:
    platform: linux/amd64 #Mac OS
    container_name: dds-db
    image: mysql:8.0.26
    command: --default-authentication-plugin=mysql_native_password --lower_case_table_names=1
    restart: always
    environment:
      MYSQL_DATABASE: dds
      MYSQL_USER: dds
      MYSQL_PASSWORD: dds1234
      MYSQL_ROOT_PASSWORD: dds1234
      MYSQL_ROOT_HOST: '%'
      DB_HOST: '0.0.0.0'
      MYSQL_DB_HOST: '0.0.0.0'
    volumes_from:
      - dbdata
    ports:
      - 3307:3306
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
  dbdata:
    platform: linux/amd64 #Mac OS
    container_name: dds-db-data
    image: mysql:8.0.26
    volumes:
      - /var/lib/mysql
    command: "true"